### ISSUE TITLE
Camera not recognized Arducam IMX477

### ISSUE THREAD

**Issue by mohammada315** [stephendade/Rpanion-server#111]
dear @stephendade 
On the video streaming page In the device field
I only have the test source

Is there a way to add arducam imx477 camera?

**Comment by stephendade** [comment]
Only the IMX219 (Official Pi Cam V2) is supported via CSI. Most USB cameras are supported.

**Comment by mohammada315** [comment]
Is there any way to use IMX477?

**Comment by mohammada315** [comment]
I tried on Jetson NX and Raspberry V4
But the camera was not found

**Comment by stephendade** [comment]
> Is there any way to use IMX477?
> 
> on my device using the pipline libcamerasrc It works alone
> 
> 
> 
> 

That's a good start. I've actually had to disable libcamerasrc cameras for now, as I've had significant stability issues with the the driver. I plan to add it back once I've figured out the issues.

**Comment by mohammada315** [comment]
I ran it as a commandline, there was no problem
thank you
