### ISSUE TITLE
ISO images without fresh install?

### ISSUE THREAD

**Issue by brunoolivieri** [stephendade/Rpanion-server#126]
When installing Rpanion from Github, the pymavlink is being installed correctly. However, the ISO image does not contain it.

I guess this line did not run on the original ISO sd card: https://github.com/stephendade/Rpanion-server/blob/b98a02f73ee7127905d6744beaf00932a4527ea5/deploy/RasPi2-3-4-deploy.sh#L62

**Comment by stephendade** [comment]
Confirmed. I'd messed up the build for the iso image for the 0.9.0 release. Note this only affects the kmz gemerator, the rest of Rapnion-server is fine. It's been fixed in #129. I will do an intermediate release in the next few weeks with the kmz generator fixes.

**Comment by stephendade** [comment]
Fixed in 0.1.0
