### ISSUE TITLE
Access point with internet connection on the same network interface

### ISSUE THREAD

**Issue by MarekZegare4** [stephendade/Rpanion-server#139]
Would be possible to implement something like this: 
https://raspberrypi.stackexchange.com/questions/89803/access-point-as-wifi-router-repeater-optional-with-bridge
to be able to be connected to internet while in AP mode?

**Comment by stephendade** [comment]
Is this over Wifi or ethernet?

**Comment by MarekZegare4** [comment]
wifi

**Comment by stephendade** [comment]
Wouldn't it be easier for all devices to just connect directly to the Internet Wifi, instead of going via the RasPi?

**Comment by MarekZegare4** [comment]
I was more thinking about using the internet on the Pi while other devices are connected to it for Mavlink stream.

**Comment by stephendade** [comment]
You can stream the MAVLink over the Internet Wifi

**Comment by MarekZegare4** [comment]
I must have missed that :p
