### ISSUE TITLE
Raspberry zero2 connected to the internet via LTE usb stick but no connection.

### ISSUE THREAD

**Issue by bbc25185** [stephendade/Rpanion-server#144]
I have a raspberry zero2 where I have installed the latest release of Rpanion.
The Hardware configuration is raspberry zero2 connected to the internet via a Huawei HiLink LTE stick and Zerotier vpn network.

The strange problem that I have identified is that the raspberry connects to the internet, it configures the Zerotier network correctly but I can access the connection only if I access the raspberry directly via wifi (both in AP mode or via Wifi router).

I can confirm that Zerotier configures correctly and that the LTE stick works as the Zerotier page is updated with the last access (Wifi disconnected) and if I connect to the Raspberry in AP, I can use the VPN address to access the configuration page.
Is there something I'm doing wrong or am I missing?
Thanks for help.

**Comment by stephendade** [comment]
> I can use the VPN address to access the configuration page. Is there something I'm doing wrong or am I missing?

That's correct, you should be able to use the VPN address to get to the config page. I'll run some tests and check this still works.

**Comment by stephendade** [comment]
Have you tried to ping the Zero2's Zerotier address via the Wifi and LTE connections? That would narrow down if it's a Zerotier problem or a Rpanion-server problem.

**Comment by stephendade** [comment]
I have found that on LTE, it can take 4-5 minutes for Zerotier to start working.

If you do an ``ifconfig`` on the Pi, does the LTE modem show up as a network adapter?

You can also try ``sudo apt install modemmanager``, as that package is sometimes required for LTE modems.

**Comment by bbc25185** [comment]
Tried...
Waited 10 minute. Not working.
ifconfig, the result:
`enx6a9e403739fa: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.143  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::8002:bb2e:18de:196b  prefixlen 64  scopeid 0x20<link>
        ether 6a:9e:40:37:39:fa  txqueuelen 1000  (Ethernet)
        RX packets 2916  bytes 2735062 (2.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2281  bytes 570371 (557.0 KiB)

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.100  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::d2bb:6be0:5129:b583  prefixlen 64  scopeid 0x20<link>
        ether e4:5f:01:94:2b:a8  txqueuelen 1000  (Ethernet)
        RX packets 1944  bytes 513784 (501.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2938  bytes 2772118 (2.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ztks5x5zr5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2800
        inet 172.30.30.20  netmask 255.255.0.0  broadcast 172.30.255.255
        inet6 fe80::30c9:fbff:fec6:c094  prefixlen 64  scopeid 0x20<link>
        ether 32:c9:fb:c6:c0:94  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 35  bytes 4478 (4.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

Tried installing Modemmanager... no change.
I notice Zerotier with 0 Rx Packets... can it be the problem???
