### ISSUE TITLE
SSID Network Names issues

### ISSUE THREAD

**Issue by spac8n00dles** [stephendade/Rpanion-server#146]
A very minor issue... Rpanion can't connect to WiFi that has space on their name. For example, it will not connect to "Pixel 3" and return "<3> unknown parameter". Of course, "Pixel3" works perfectly.

**Comment by stephendade** [comment]
Thanks for reporting. I'll get that fixed up in the next week or so.

**Comment by spac8n00dles** [comment]
Champion! I love your software :) Hopefully I will get some time to help on improving it

**Comment by stephendade** [comment]
I've pushed a fix in #152. Can you check if that works for you?

**Comment by stephendade** [comment]
Fix is now merged
