### ISSUE TITLE
USB-Connection not working anymore

### ISSUE THREAD

**Issue by Lehp** [stephendade/Rpanion-server#151]
Hey Steven, I'm currently building a solar-drone and found your software very useful. I managed like 3 months ago to connect my MATEK-h743 over Its usb-c port to the usb-A-3 port of my raspberry pi.
Then I was able to connect with rpanion-server to the flight controller, and mission-Planner to the controller. But I just can't connect anymore. I tried for 6h+ and did every thing I could imagine. I would be very thankful for your support.

My best guess: 
With updates of rasbianOS, path of usb-serial-connections moved to folder /dev/bus/usb 
![image](https://github.com/stephendade/Rpanion-server/assets/40690143/e94bd6fa-5390-40be-be69-2cdff559993c)

Latest update of rpanion-server: 10/08/2023

What I tried: 

- Bad usb-cable (mine works with windows + mission-planner directly)
- Every baud rate with  mavlink 1 + 2
- manually triggering Serial-modules-install
- Booting matek-h743 in boot-mode

**Comment by stephendade** [comment]
Thanks for the investigation. That is indeed the case :(

I've pushed a fix to #153. Can you check if that works for you?
