### ISSUE TITLE
Error node_modules/node-mavlink/dist/lib/mavesp.js

### ISSUE THREAD

**Issue by hilarioaraujo** [stephendade/Rpanion-server#154]
I am trying the Rpanion server in Raspberry 4 and LattePanda Delta 3.

When I run the code: npm run testback I receivd 2 errors in the node_modules.

![Screenshot from 2023-08-16 13-19-00](https://github.com/stephendade/Rpanion-server/assets/47309365/b9615718-3774-44cb-94bf-3e5f104f02d6)

![Screenshot from 2023-08-16 13-22-39](https://github.com/stephendade/Rpanion-server/assets/47309365/f571e3ed-a7de-4dcf-a057-a049f2de27e7)

I have to delete the "?" from node_modules/node-mavlink/dist/lib/mavesp.js and  node_modules/@serialport/dist/serialport-mock/index.js to succeed test.

**Comment by stephendade** [comment]
What version of nodejs are you running?
