### ISSUE TITLE
Some problems in configuration and use

### ISSUE THREAD

**Issue by lin19968** [stephendade/Rpanion-server#166]
How to solve this problem
![_1070443942_IMG20231005165632_1696496193000_xg_0](https://github.com/stephendade/Rpanion-server/assets/147042644/456e4163-3e45-4f58-93fc-fc105c4bb28b)

**Comment by lin19968** [comment]
When I use the serial stream played by VLC, it stops playing for 2 seconds, how can I solve this?

**Comment by lin19968** [comment]
I'm using Ubuntu 22.04

**Comment by stephendade** [comment]
The ``deprecated`` warnings are normal during installation. They don't affect the operation of Rpanion-server.

For the video, which camera and settings are you using?

**Comment by lin19968** [comment]
![image](https://github.com/stephendade/Rpanion-server/assets/147042644/35411fcf-28e6-4087-972a-29126715098d)
I use this camera, and when I use the official Raspberry Pi image, I can output video normally, but I can't configure it myself

**Comment by stephendade** [comment]
I need the other settings on the page too. Also the actual name of the camera.

>  I use this camera, and when I use the official Raspberry Pi image, I can output video normally, but I can't configure it myself
I'm not sure what you mean by "can't configure it myself"

**Comment by lin19968** [comment]
![image](https://github.com/stephendade/Rpanion-server/assets/147042644/c7a1f7d8-7be4-44ac-a74e-2a827e03ca1a)
I use Ubuntu 22.04 system to run Rpanion-server, I can't output video, I burn the official configuration Raspberry Pi image to output video, I don't know what the problem is.

**Comment by lin19968** [comment]
![_-2106599389_IMG20231006123553_1696566954000_xg_0](https://github.com/stephendade/Rpanion-server/assets/147042644/c5251a60-6533-4d01-9d74-c3fe238d9a8b)
This is the packaging of the camera

**Comment by stephendade** [comment]
I've confirmed the freezing happen when using RTSP. Can you test RTP too - that works ok for me.

**Comment by lin19968** [comment]
It is also impossible to output video using RTP

**Comment by stephendade** [comment]
> I use Ubuntu 22.04 system to run Rpanion-server, I can't output video, I burn the official configuration Raspberry Pi image to output video, I don't know what the problem is.

I've had a chance to run some tests with an MJPEG source camera.
- Ubuntu22 is quite unreliable with streaming. I don't recommend you use it.
- I had no issues using a recent version of RasPiOS, or the 0.1.0 image in the "releases" tab.

**Comment by stephendade** [comment]
Update: I've added a patch to make streaming more stable on Ubuntu22 - I changed to software x264 encoding and it works much better.

**Comment by lin19968** [comment]
Now that the problem has been solved, thank you very much

**Comment by lin19968** [comment]
I tried to install the Ubuntu 20.04 desktop version of the system, but I couldn't find the corresponding .img file online, so I had to choose to install the 22 system
