### ISSUE TITLE
No video feed thru UDP with RTP

### ISSUE THREAD

**Issue by ltrzcinski** [stephendade/Rpanion-server#175]
There is no video feed thru UDP via RTP, tried different bitrate/resolution options but no success.

(RTSP works very good)

![UDP error](https://github.com/stephendade/Rpanion-server/assets/64522330/75e4c660-5996-47c9-a303-8e781c959b5d)

**Comment by bbc25185** [comment]
I see Destination IP 127.0.0.1
You need to change the IP address from 127.0.0.1 (its the IP of LocalHost) to the IP of the machine where QGC run.

**Comment by lida2003** [comment]
> You need to change the IP address from 127.0.0.1 (its the IP of LocalHost) to the IP of the machine where QGC run.

I think it's [ Feature Request: send VIDEO_STREAM_INFO mavlink messages to GCS #169 ](https://github.com/stephendade/Rpanion-server/issues/169).

**Comment by Navneet2103** [comment]
my feed comes at low latency but grey in colour! 

![Image](https://github.com/user-attachments/assets/d37f55a8-5bba-4c1f-8610-86157e34ddcf)

**Comment by stephendade** [comment]
> my feed comes at low latency but grey in colour!

That's due to H264 compression artifacts. You'll need to wait ~30sec for the video stream to stabilise.
