### ISSUE TITLE
Integrating the raspberry Pi 4 

### ISSUE THREAD

**Issue by FrMohamedFaris** [stephendade/Rpanion-server#178]
After writing the rpanion-serevr image in the Sd card. How can I get log in through the Putty and what's next step I've to do ?

**Comment by stephendade** [comment]
https://www.docs.rpanion.com/software/rpanion-server#using

**Comment by FrMohamedFaris** [comment]
Hi stephendade, 

the thingh is actually "How to connect the raspberry pi 4 after the image written in Sd crad through Putty bash"
And I can't able understand How it was done and send step by step process to acheive it.

**Comment by stephendade** [comment]
I'm not sure what you're asking. After writing the image to SD Card, the Wifi hotspot and Rpanion-server will be started automatically on boot.
