### ISSUE TITLE
Can't set "Maximum Bitrate" beyond 10MB on Raspberry Pi3B+

### ISSUE THREAD

**Issue by lida2003** [stephendade/Rpanion-server#191]
if I set Maximum Bitrate more than 10Mbps, such as 11Mbps. It will not take effect and blank the web page.

It'll be useful for high rate settings, as 720P@10Hz takes roughly about 7~8Mbps.

Tried `gpu_mem=196`, no luck!

>![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/59228e6d-c5aa-47c1-88ad-97a39d5aa60c)

>![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/af5946d1-3ac4-4f21-8f5f-34307637c656)

**Comment by stephendade** [comment]
That's deliberate - I'd set the max allowable bitrate to 10Mbps. I've now upped this to 60Mbps. Fixed in #193.

**Comment by lida2003** [comment]
50M/30M/25M ==> VLC can't work
10M/20M ==> VLC works

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/645f527a-66fe-40e2-9cbe-570dc5253225)

**Comment by stephendade** [comment]
> 50M/30M/25M ==> VLC can't work
10M/20M ==> VLC works

Yep, that's expected. The x264 hardware encoder on the Pi can do a maximum of 20Mbps.

The encoder is level 4 compliant, and according to https://blog.mediacoderhq.com/h264-profiles-and-levels/, that equates to 20Mbps.

**Comment by lida2003** [comment]
I checked link, it seems level 4 can run over 20Mbps when in different profiles. Please correct me if I'm wrong.

**Comment by stephendade** [comment]
In #195 I've updated to using the "high" profile, allowing for up to 50Mbps. Tested on a 3b+ and works well.

Note that the "bitrate" setting in the web GUI is a **maximum** number. The actual bitrate depends alot on the movement in the frame.

**Comment by lida2003** [comment]
> In #195 I've updated to using the "high" profile, allowing for up to 50Mbps. Tested on a 3b+ and works well.

I would be nice to have 50Mbps.

**Comment by stephendade** [comment]
> I would be nice to have 50Mbps.

I meant "up to and including 50Mbps"
