### ISSUE TITLE
Feature Request: pan-tilt gimbal controls

### ISSUE THREAD

**Issue by lida2003** [stephendade/Rpanion-server#196]
I think a pan-tilt gimbal conrol is very thoughtful design. 

This is my video about this 2D gimbal, https://www.youtube.com/watch?v=omBjam52Hq0

So what I'm proposed here: is it possible for Rpanion to intergrate this feature? And then it might be controlled by MP or QGC.

- https://ardupilot.org/copter/docs/common-mount-targeting.html
- https://ardupilot.org/copter/docs/common-camera-controls.html

There is pan-tilt HAT board for RaspberryPi and jetson.

- 【Wiki】www.waveshare.net/wiki/Pan-Tilt_HAT 
- 【Github】https://github.com/waveshare/Pan-Tilt-HAT
- 【Aliexpress】https://www.aliexpress.com/i/2251832799696289.html?gatewayAdapt=4itemAdapt

---
EDIT:
related features: 
- https://github.com/stephendade/Rpanion-server/issues/169
- https://mavlink.io/en/services/gimbal_v2.html

It is something like "Standalone Integrated Camera/Gimbal"

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/e054124f-df1a-4713-ab40-40d1b6ebc9fa)

**Comment by stephendade** [comment]
For the pan/tilt, you connect the gimbal directly to the flight controller and control it from there. I'm not sure why you'd need to go via the RPi?

**Comment by lida2003** [comment]
> For the pan/tilt, you connect the gimbal directly to the flight controller and control it from there. I'm not sure why you'd need to go via the RPi?

Currently, camera and [gimble](www.waveshare.net/wiki/Pan-Tilt_HAT) are all connected to Rpi. So I think it's rather simple for communication.

GCS ==> Rpi ==> pan/tilt

**Comment by stephendade** [comment]
Using PWM servo pan/tilt with ArduPilot: https://ardupilot.org/copter/docs/common-camera-gimbal.html#common-camera-gimbal

I do plan to add in the ``VIDEO_STREAM_INFO`` MAVLink messages, as it should allow better GCS management of the camera video stream.

**Comment by lida2003** [comment]
> Using PWM servo pan/tilt with ArduPilot: https://ardupilot.org/copter/docs/common-camera-gimbal.html#common-camera-gimbal
> 

Hmmmm... I see.

 Here is a scenario I'm considering:

a. pan/tilt camera, looking for a specific vechicle
b. now, the camera locks the vechicle at a pan/title angle
c. companion computer need to tell ardupilot to follow and tracking the vechicle
d. during the process of following and tracking, the camera should be always looking at vechicle

The quesiton is what kinds of MAVLink API or message should be used during the process? Any idea or tips?

**Comment by stephendade** [comment]
So the camera is running some sort of image detection to find the car?

So a typical workflow would be:

1.  Camera detects the vehicle
2.  Camera software calculates relative pitch and yaw angles from drone to vehicle
3.  Camera software sends these values to ArduPilot via MAVLink message (https://ardupilot.org/dev/docs/mavlink-gimbal-mount.html#mav-cmd-do-gimbal-manager-pitchyaw-to-move-to-a-desired-angle-or-at-a-desired-rate)
4.  Repeat as needed

**Comment by lida2003** [comment]
Ardupilot has this kind of features, which has more info about FC(navigation). Stick to the following diagram might be a good choice.

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/b6f88632-c6d6-4132-a768-9871c0451f93)
