### ISSUE TITLE
High CPU Usage on startup from NPM service

### ISSUE THREAD

**Issue by bbc25185** [stephendade/Rpanion-server#198]
I don't know if it's intentional or not, but when I turn it on I find the NPM service using the CPU a lot (screenshot attached) for about 5 minutes.
After 5 minutes the NPM service closes and CPU usage returns to normal levels (A few percent).
Can anyone explain to me why???
Thanks in advance for your answers.

Hardware:
Raspberry Zero 2
Rpanion version 0.10.0
Only configuration i touched: Connection to my WiFi Network

![Screenshot 2024-01-30 175644](https://github.com/stephendade/Rpanion-server/assets/18754581/da81e3e4-7dc0-4cb7-b760-f07b0a213285)

**Comment by stephendade** [comment]
Thanks for reporting - I'll take a look in the next couple of days.

**Comment by stephendade** [comment]
This is what I'm getting after 10min running latest master - no massive CPU usage of my Pi Zero2:

![Screenshot from 2024-02-05 09-11-40](https://github.com/stephendade/Rpanion-server/assets/1731976/a9306084-01b3-4850-a43f-a11c36a00ec6)

Could you try again with latest master and see if you still have the issue?

**Comment by bbc25185** [comment]
Tried with latest master:
First 5 minute: Full cpu usage::
![Screenshot 2024-02-05 161345](https://github.com/stephendade/Rpanion-server/assets/18754581/ebf8d749-46ca-461b-9fa2-34f20f66c826)
after 5 minute of uptime:
![Screenshot 2024-02-05 161803](https://github.com/stephendade/Rpanion-server/assets/18754581/850090f7-ee0a-4a0e-b4b6-f8c9f3d87e76)

**Comment by stephendade** [comment]
I'll need some logfiles to diagnose the issue further:
- ~/Rpanion-server/logs/app.log
- The output of ``journalctl -u rpanion.service -n 200``
- The output of ``sudo systemctl status rpanion.service``

**Comment by bbc25185** [comment]
[Journalctl -u rpanion.service -n 200.txt](https://github.com/stephendade/Rpanion-server/files/14193927/Journalctl.-u.rpanion.service.-n.200.txt)
[systemctl status rpanion.service.txt](https://github.com/stephendade/Rpanion-server/files/14193928/systemctl.status.rpanion.service.txt)
[app.log.txt](https://github.com/stephendade/Rpanion-server/files/14193929/app.log.txt)

The requested 3 files!

**Comment by stephendade** [comment]
It looks like there are some errors with the streaming video. If you don't stream video, do you get the same issue?

**Comment by bbc25185** [comment]
Video streaming stopped. Same problem: CPU usage at 100% until the 5th minute.
logfiles attached:
[app.log no video.txt](https://github.com/stephendade/Rpanion-server/files/14210087/app.log.no.video.txt)
[systemctl status rpanion.service no video.txt](https://github.com/stephendade/Rpanion-server/files/14210089/systemctl.status.rpanion.service.no.video.txt)
[journal -u rpanion.service -n 200 no video.txt](https://github.com/stephendade/Rpanion-server/files/14210090/journal.-u.rpanion.service.-n.200.no.video.txt)

**Comment by stephendade** [comment]
It's due to this : https://github.com/nodejs/node/issues/49937

A ``sudo rpi-update`` to upgrade the kernel will fix the issue.

**Comment by bbc25185** [comment]
I confirm that updating the kernel solved the problem.
Thank you!
