### ISSUE TITLE
Not enough RAM for building on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by codeceptsDE** [stephendade/Rpanion-server#208]
I'm having trouble building on a Raspberry Pi 3B+, 1Gb RAM is insufficient to build mavlink-routerd.

I had to change `deploy/build_mavlinkrouter.sh` from 
```
if [ $(free -m | awk '/^Mem:/{print $2}') -le 500]; then
    ninja -j 2 -C build
else
    ninja -C build
fi
```
to `if [ $(free -m | awk '/^Mem:/{print $2}') -le 950 ]; then` to make it work. 
It's a bit slower, but at least it doesn't crash the Pi.

Maybe the same should apply to `deploy/build_rpanion.sh`, but I found it not to be necessary (right now). But it's cutting it close.

**Comment by stephendade** [comment]
Thanks for the report. Happy to accept a PR with those changes.

**Comment by timtuxworth** [comment]
Wouldn't just increasing the swap space work? The default is only 100k.
