### ISSUE TITLE
[Feature Request] IP bind to mac when Rpanion used as WiFi AP

### ISSUE THREAD

**Issue by lida2003** [stephendade/Rpanion-server#214]
As I'm using RTP, QGroundControl/MissionPlanner on mobile device will change if there are quite a lot of device in the network.

Is it possible to bind the IP of QGroundControl/MissionPlanner to MAC when Rpanion is used as a WiFi Access Point.

Or there is any other alternative way to use RTP without setting ip address on web panel?

PS: I noticed there is multicast RTP address, but I don't know how.

---EDIT

As I use Pi3B+ for Rpanion, there are two network:

Rpanion AP: 10.0.2.x
Ethernet: 192.168.1.x
Laptop:192.168.1.9
mobile QGC: 192.168.1.5

If I set RTP to broadcast address 192.168.1.255, it seems RTP server is in infinite loop(restart), as the video is on/black/on/black....

**Comment by stephendade** [comment]
> Is it possible to bind the IP of QGroundControl/MissionPlanner to MAC when Rpanion is used as a WiFi Access Point.

There should be a setting on your laptop to specify a static IP address instead of using DHCP for the Rpanion network.

> If I set RTP to broadcast address 192.168.1.255, it seems RTP server is in infinite loop(restart), as the video is on/black/on/black....

Multicast RTP isn't supported at this time.

**Comment by lida2003** [comment]
> There should be a setting on your device to specify a static IP address instead of using DHCP for the Rpanion network.

OK, it's a work around approach. And it's OK for me.
