### ISSUE TITLE
Can't connect to FC through serial port

### ISSUE THREAD

**Issue by lida2003** [stephendade/Rpanion-server#215]
I don't know why pop up this error message? 
Is there any configuration, I should pay attention?

BTW, RX/TX has been switched, it didn't work out.

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/047c1e73-c607-4a52-a112-2ad71ab2e167)

![b066e43ec3f64af50cbea143f36deba](https://github.com/stephendade/Rpanion-server/assets/1296171/b82c2707-9c0c-464b-a1a1-aa18c2dddab3)

**Comment by lida2003** [comment]
Hummmm.....

It seems that there is something wrong in file read/write permission???

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/590f89d6-ca75-4ff2-9726-10b7929c44d2)

**Comment by lida2003** [comment]
a) Re-installed with latest git code, json error gone.
b) If I use an usb-serial adapter, it's OK to communicating with FC @ 57600bps
c) switched to Rpanion, I still didn't get FC connected. 

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/b2ab943d-f40d-407b-bd22-5c41ee3cf917)

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/90bc9c9d-78d5-486f-84de-9cc09e8015d3)

**Comment by stephendade** [comment]
> c) switched to Rpanion, I still didn't get FC connected. (Rx/Tx switched useless)

Can you give a full list of all detected Serial devices?

**Comment by lida2003** [comment]
> Can you give a full list of all detected Serial devices?

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/7f856008-fb51-4eb9-b531-4e9c3bc95b6a)

**Comment by stephendade** [comment]
> BTW, I didn't find the device on dev dir.

Try ``ls /dev`` to get the full list

**Comment by lida2003** [comment]
> > BTW, I didn't find the device on dev dir.
> 
> Try `ls /dev` to get the full list

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/d1fa3f9b-32d5-4dee-8398-65ac7b448e83)

I can get data from linux console, hardware should be OK

![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/7c98f734-5dff-4e1d-9a3b-aeee8d8d968c)

**Comment by lida2003** [comment]
Configure as following steps:

1) start telemetry
![6dd547b540445907c56fa0f7536f411](https://github.com/stephendade/Rpanion-server/assets/1296171/9d347f6d-3f33-4ff5-b78a-0929c6e40517)
2)configure  QGC
![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/95a60b42-6666-4643-b539-5e093957b73f)
3) connect
![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/6ffb19b7-0ef1-4e9d-b882-a20fa88416b6)
4) check QGC telemetry status  ,,,,  "disconnect"???
![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/4ed04641-4caf-490d-9a67-ce4c52145481)

**Comment by lida2003** [comment]
I have got a video, it seems that  rpanion has recevied characters from UART, but it failed to parse.
https://github.com/stephendade/Rpanion-server/assets/1296171/483c64de-2893-4626-a7c8-fcb547d1dc28

**Comment by stephendade** [comment]
Can you try ``/dev/serial0`` with MAVProxy on the RPi? This would confirm if the serial port is working properly or not.

**Comment by lida2003** [comment]
> Can you try `/dev/serial0` with MAVProxy on the RPi? This would confirm if the serial port is working properly or not.

Yes, I have connected serial to computer, it works fine with mission planner.

**Comment by stephendade** [comment]
Ok, so it's a configuration issue on the RPi?

What model RPi are you using?
Can you post the contents of your ``/boot/config.txt`` and ``/boot/cmdline.txt``
Maybe try connecting on ``dev/serial1`` using MAVProxy, just to confirm it's not a mixed up serial port?

**Comment by lida2003** [comment]
Yeah, it Rpi serial config issue. And I'm using RPi 3B+ hardware.

After searching/reading links, I finally get it running.

A) cmdline.txt to remove "console" config.

```
$ cat /boot/cmdline.txt
root=PARTUUID=6ed124ff-02 rootfstype=ext4 fsck.repair=yes rootwait
```

B) Adding following lines to use the correct uart.

```
enable_uart=1
dtoverlay=uart1
dtoverlay=disable-bt
core_freq=250
dtoverlay=pi3-miniuart-bt
```

@stephendade althouhg it's running, I still have a few quesiton here.

a) I have looked into /boot, there is no dtd file called "pi3-miniuart-bt", quite confused about `dtoverlay=pi3-miniuart-bt`, Can I remove `dtoverlay=pi3-miniuart-bt`?
b) There are two ways for using Rpi serial: hardware/software UART. Software is related to `core_freq=250`, Can you help to let me configure to use hardware uart config?

**Comment by stephendade** [comment]
The 3B+ can be a bit strange for UART config sometimes.

In theory, you should only need:

> A) cmdline.txt to remove "console" config.
> 
> $ cat /boot/cmdline.txt
> root=PARTUUID=6ed124ff-02 rootfstype=ext4 fsck.repair=yes rootwait

and

> B) Adding following lines to use the correct uart.
> 
> enable_uart=1

Otherwise, I might need to add a section in the documentation about the 3B+ "proper" config.

**Comment by lida2003** [comment]
> The 3B+ can be a bit strange for UART config sometimes.
> 
> In theory, you should only need:
> 
> > A) cmdline.txt to remove "console" config.
> > $ cat /boot/cmdline.txt
> > root=PARTUUID=6ed124ff-02 rootfstype=ext4 fsck.repair=yes rootwait
> 
> and
> 
> > B) Adding following lines to use the correct uart.
> > enable_uart=1
> 
> Otherwise, I might need to add a section in the documentation about the 3B+ "proper" config.

RPi3B+ need to do more

- `sudo systemctl disable hciuart`
- add `enable_uart=1` and `core_freq=250`

And now, it's quite OK. 

https://www.bilibili.com/video/BV1uC41157q2/

**Comment by lida2003** [comment]
@stephendade I strongly recommend to use USB2TTL device. As it's NOT stable to use RPi3B+ TTL

- Config USB2TTL
![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/0af13a1d-12c9-49af-9b36-13f8b4ebebce)

- Pi's TTL
![图片](https://github.com/stephendade/Rpanion-server/assets/1296171/3d6d3309-5280-4c1d-8067-9a0b5ed0b765)

**Comment by stephendade** [comment]
I've just used the Rpanion-server 0.10.0 image on a 3B+, with a Cube Orange flight controller TELEM2 port connected to the GPIO UART on the Pi.

Running at 57600 baud, zero issues. Worked the first time.

So I'm not sure why you're having issues.

**Comment by lida2003** [comment]
> 
> Running at 57600 baud, zero issues. Worked the first time.
> 
> So I'm not sure why you're having issues.
> 


Maybe 57600, I'm running 115200
