### ISSUE TITLE
[Feature Request] Add UDP Video Stream to support / qgroundcontrol

### ISSUE THREAD

**Issue by dannyb131** [stephendade/Rpanion-server#22]
could you add udp video stream to support qgroundcontrol.
in my testing udp reduces the latency by upto100ms that the currently only available option in qgroundcontrol is rtsp that works with Rapnion.
 the pipeline I've found that works best:
gst-launch-1.0 rpicamsrc bitrate=1000000 ! 'video/x-h264,width=640,height=480' ! h264parse ! queue ! rtph264pay config-interval=1 pt=96 ! udpsink host=10.0.2.243 port=5600

[Video of my tests](https://drive.google.com/file/d/1-fUmTDhrvgWUnFYCnNzOS5YWk7qCbsiw/view?usp=sharing
) running on a raspberry pi zero w, and QGC on an low spec old i3 laptop

[https://docs.qgroundcontrol.com/master/en/SettingsView/General.html#video](https://docs.qgroundcontrol.com/master/en/SettingsView/General.html#video)
[https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoReceiver/README.md](https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoReceiver/README.md)

Thanks

**Comment by stephendade** [comment]
Thanks for investigating! I'll add it in the coming weeks.

**Comment by stephendade** [comment]
I've got the feature working in #24 and is working for me. Are you able to test too?

**Comment by dannyb131** [comment]
Hi Stephen,

seems to be working! good stuff!


Thanks

**Comment by stephendade** [comment]
Cool, thanks for testing! I'll merge it in
