### ISSUE TITLE
Is segmav possible to perform simple obstacle avoidance driving within the field of view

### ISSUE THREAD

**Issue by lida2003** [stephendade/Rpanion-server#230]
Hi @stephendade 

I have noticed your segmav, using semantic segmentation running on a Jetson Nano.
Is segmav possible to perform simple obstacle avoidance driving within the field of view?

I want to use it on my jetson orin nano board to drive my akm rover.

```
Cam ==> Rpi3B+ <==> 4G LTE (or WiFi)  <==> Jetson Orin Nano
                    |
                   FC   --  Rover
```

**Comment by stephendade** [comment]
It doesn't do object avoidance. It does object tracking, where the rover will follow a specified segmentation class. So the opposite of what you want.

**Comment by lida2003** [comment]
Actually, I need let rover do 3 things:

1. tracking the road
2. do simple object avoidance
3. following  a selected person

And this demo can do 1) , I'm looking for code to handle 1)2)3), do you have any suggestion?

**Comment by stephendade** [comment]
No suggestion, sorry.
