### ISSUE TITLE
question about Wifi hostpot

### ISSUE THREAD

**Issue by alireza787b** [stephendade/Rpanion-server#238]
Hi
Thanks for the great app
I have a question. Can't we just have a wifi hotspot and let the pi get an IP from a router that it is connected to and even get internet from that and we use the private IP to access the web interface?

**Comment by stephendade** [comment]
Yes, sure you can do that.

**Comment by stephendade** [comment]
> i tried installing the image you provided with Raspberry Imager but after installation no wifi hotspot appeared

Then something went wrong with the flashing process. Note you need to disable all customisation options when using Raspberry Imager

Documentation is available at https://www.docs.rpanion.com/software/rpanion_server_v010
