### ISSUE TITLE
Feature request: Add possibility to enable/set listening TCP port of mavlink router

### ISSUE THREAD

**Issue by nwalser** [stephendade/Rpanion-server#34]
It would be awesome to be able to enable/set the listening port of the mavlink-router.

This would be required in a scenario where to GCS wants to connect via WLAN network directly to the mavlink network.

GCS -> TCP (over WLAN) -> Rpanion-server

Please let me know if I got something wrong in the architecture and it is not intended to use it this way.
For now I got it working by changing the line with the desired port:

https://github.com/stephendade/Rpanion-server/blob/fcc8e872001a492f8a465d0fa120d3af92296fdf/server/flightController.js#L252

**Comment by stephendade** [comment]
Is there a particular reason you want to use TCP? Mavlink telemetry is almost always sent over UDP (outside of simulation)

**Comment by nwalser** [comment]
I just wanted to test if the  rpanion-server works correctly. And to do that I expected that I could connect with the rpanion server via TCP without the need to run a router software that the drone connects to on my computer.

In my final setup I wont use this option, because it will look more like this:
Pixhawk 4 (Ardupilot) ---(UART)--> RaspberryPi Zero (Rpanion-server) ---(UDP)--> Server on the internet ---(UDP)--> GCS

I thought it would be usefull in the case when you want to connect to the drone via the WLAN without the need to run any software on your PC (except the GCS of your choice).

**Comment by stephendade** [comment]
Ok, I'll look at adding that option.
