### ISSUE TITLE
Video streaming settings

### ISSUE THREAD

**Issue by scala93** [stephendade/Rpanion-server#54]
I've just tested out the new release. A lot of improvements! 
But for the streaming section both resolution and UDP IP address reset to default at every start up. I tried to set my own values and reboot as the 0.8 guide says but it did not work.

**Comment by stephendade** [comment]
Thanks for reporting this - It's now been fixed.

**Comment by lorenzing** [comment]
Hi, are the ISOs already updated?

**Comment by stephendade** [comment]
> Hi, are the ISOs already updated?

The ISOs are only updated for major releases. Follow the instructions at https://github.com/stephendade/Rpanion-server#updating to update to the latest code of Github

**Comment by scala93** [comment]
Stephen I've also found out that when changing resolution it zoomes instead of really changing resolution.
Moreover, once I disconnect the connection it does not restart the video link (using zerotier and qgc).

**Comment by stephendade** [comment]
> Stephen I've also found out that when changing resolution it zoomes instead of really changing resolution.

What camera is this with? The Raspberry Pi Camera does in some cases crop/zoom the image, depending on the selected resolution and framerate (see https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes)

**Comment by scala93** [comment]
> > Stephen I've also found out that when changing resolution it zoomes instead of really changing resolution.
> 
> What camera is this with? The Raspberry Pi Camera does in some cases crop/zoom the image, depending on the selected resolution and framerate (see https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes)

It is a raspberry pi camera V2. And it's cropping as resolution goes higher. So no solution for that? And for the non reconnection issue what do you think?

**Comment by stephendade** [comment]
> And for the non reconnection issue what do you think?

That should now be fixed. Give it a test and see if that works for you.

> It is a raspberry pi camera V2. And it's cropping as resolution goes higher. So no solution for that?

That's a function of the camera itself. Nothing I can do to fix that.

**Comment by scala93** [comment]
> > And for the non reconnection issue what do you think?
> 
> That should now be fixed. Give it a test and see if that works for you.
> 
> > It is a raspberry pi camera V2. And it's cropping as resolution goes higher. So no solution for that?
> 
> That's a function of the camera itself. Nothing I can do to fix that.

From bench test streaming video reconnection issue has been solved.
