### ISSUE TITLE
[Feature Request] VPN web interface

### ISSUE THREAD

**Issue by lorenzing** [stephendade/Rpanion-server#59]
Hello, 
hoping to propose something useful for other users, I wanted to ask if you can insert a VPN page in the web interface. 
As a vpn client I use vpnc which to work takes data from /etc/vpnc/rpanion.conf within which they must be specified:
```
IPSec gateway myhost.net
IPSec ID vpn_user
IPSec secret TANrpS1y34hHHJGIS4
IKE Authmode psk
Xauth username vpn_user
Xauth password <passwort>
local port 0
DPD idle timeout (our side) 0
```
The tunnel test command are:
`sudo vpnc rpanion.conf
`
To stopping tunnel:
`sudo vpnc-disconnect
`

If you could edit the values of this file in the web interface it would be very convenient for me without having to connect with ssh.
I have also seen that several people use Zero-Tier and you could also enter for them in this page the possibility to put their NETWORKID.

I insert a sample to explain myself better, taking inspiration from a service that already exists:
![sample](https://user-images.githubusercontent.com/10693529/147665165-c3dad0d2-56fa-4904-966f-07535cbec171.png)

Thank you so much anyway, Lorenzo.

**Comment by giyowiy** [comment]
Wow that would be a great feature! Hope it can be implemented soon

Gyoway

**Comment by stephendade** [comment]
Sure - I'll look at adding that in the next few months.

**Comment by lorenzing** [comment]
Thank you so much @stephendade and congratulations on your great work!

**Comment by hyperion11** [comment]
hello! when version with VPN will be released?

**Comment by stephendade** [comment]
I'm actually writing the VPN feature at the moment, for Wireguard and Zerotier. I'm hoping it'll be done in the next month.
