### ISSUE TITLE
V 0.9 to do list

### ISSUE THREAD

**Issue by stephendade** [stephendade/Rpanion-server#69]
This list will track the to-be-completed features/fixes for V0.9:

- [x] Add VPN interface
- [x] Cloud upload of logs ~~and other files~~
- [ ] Multi-camera streaming
- [ ] Option to add username/password login to Rpanion
- [x] Wifi scanning for easy adding of networks
- [ ] Default to hotspot if no saved Wifi networks in range
- [ ] In hotspot mode, automatically add each dhcp client as a UDP endpoint for telemetry
- [x] Better explain that UDP endpoints are the remote address
- [ ] Add way for users to add publickeys for cloud upload
- [x] Show current pubkey for easy copy/pasting to cloud storage
- [ ] Allow firmware upload - both custom and standard firmwares
- [x] Rpanion updater for ~~both stable and~~ github latest
- [ ] Add help section
- [x] Rework wifi network to "Connect to Wifi network" and "Create hotspot"
- [x] Add flight controller output to udp broadcast to network

**Comment by stephendade** [comment]
Given it's been a long time since the last release and I'm finding I have less time these days, I'll cut the feature list for V0.9 to what is currently done, plus a VPN GUI for Wireguard and Zerotier.

Plan is to complete the VPN GUI in the next couple of weeks, then start beta testing V0.9

The uncompleted features in the list I'll defer to a future release.

**Comment by stephendade** [comment]
Ok, VPN GUI is done :)

That's all major features done for V0.9, so I'll start with detailed checks and testing on a Pi (Ras Pi OS and latest LTS Ubuntu) and (possibly) a Jetson Nano.

**Comment by mohammada315** [comment]
We are eager to use as soon as possible
thank you Rpanion developers

**Comment by stephendade** [comment]
0.9 is released, so closing. Will make a new list for V0.95
